---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dra-driver-sriov.fullname" . }}-role
  namespace: {{ include "dra-driver-sriov.namespace" . }}
rules:
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["get"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims/status"]
  verbs: ["get","list","update","patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]  # Cluster-scoped resource, needs cluster permissions
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["get"]
- apiGroups: ["sriovnetwork.openshift.io"]
  resources: ["sriovresourcefilters"]
  verbs: ["get", "list", "watch"]  # SriovResourceFilter resources
