---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dra-driver-sriov.fullname" . }}-kubeletplugin
  namespace: {{ include "dra-driver-sriov.namespace" . }}
  labels:
    {{- include "dra-driver-sriov.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubeletplugin
spec:
  selector:
    matchLabels:
      {{- include "dra-driver-sriov.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kubeletplugin
  {{- with .Values.kubeletPlugin.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.kubeletPlugin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dra-driver-sriov.templateLabels" . | nindent 8 }}
        app.kubernetes.io/component: kubeletplugin
    spec:
      hostNetwork: true
      {{- if .Values.kubeletPlugin.priorityClassName }}
      priorityClassName: {{ .Values.kubeletPlugin.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dra-driver-sriov.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kubeletPlugin.podSecurityContext | nindent 8 }}
      containers:
      - name: plugin
        securityContext:
          {{- toYaml .Values.kubeletPlugin.containers.plugin.securityContext | nindent 10 }}
        image: {{ include "dra-driver-sriov.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["dra-driver-sriov"]
        resources:
          {{- toYaml .Values.kubeletPlugin.containers.plugin.resources | nindent 10 }}
        {{/*
          A literal "0" will allocate a random port. Don't configure the probe
          with the same literal "0" since that won't match where the service is
          actually running.
        */}}
        {{- if (gt (int .Values.kubeletPlugin.containers.plugin.healthcheckPort) 0) }}
        livenessProbe:
          grpc:
            port: {{ .Values.kubeletPlugin.containers.plugin.healthcheckPort }}
            service: liveness
          failureThreshold: 3
          periodSeconds: 10
        {{- end }}
        env:
        - name: CDI_ROOT
          value: /var/run/cdi
        - name: KUBELET_REGISTRAR_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: KUBELET_PLUGINS_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.kubeletPlugin.containers.plugin.healthcheckPort }}
        - name: HEALTHCHECK_PORT
          value: {{ .Values.kubeletPlugin.containers.plugin.healthcheckPort | quote }}
        {{- end }}
        # Logging configuration
        {{- if .Values.logging.level }}
        - name: V
          value: {{ .Values.logging.level | quote }}
        {{- end }}
        {{- if .Values.logging.format }}
        - name: LOG_FORMAT
          value: {{ .Values.logging.format | quote }}
        {{- end }}
        {{- if .Values.logging.alsologtostderr }}
        - name: ALSOLOGTOSTDERR
          value: {{ .Values.logging.alsologtostderr | quote }}
        {{- end }}
        {{- if .Values.logging.logFile }}
        - name: LOG_FILE
          value: {{ .Values.logging.logFile | quote }}
        {{- end }}
        volumeMounts:
        - name: plugins-registry
          mountPath: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: plugins
          mountPath: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
        - name: cdi
          mountPath: /var/run/cdi
      volumes:
      - name: plugins-registry
        hostPath:
          path: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
      - name: plugins
        hostPath:
          path: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
      - name: cdi
        hostPath:
          path: /var/run/cdi
      {{- with .Values.kubeletPlugin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
