{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dra-driver-sriov.serviceAccountName" . }}
  namespace: {{ include "dra-driver-sriov.namespace" . }}
  labels:
    {{- include "dra-driver-sriov.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
