// Code generated by MockGen. DO NOT EDIT.
// Source: host.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_host.go -source host.go
//

// Package mock_host is a generated GoMock package.
package mock_host

import (
	reflect "reflect"

	v1alpha1 "github.com/SchSeba/dra-driver-sriov/pkg/api/virtualfunction/v1alpha1"
	host "github.com/SchSeba/dra-driver-sriov/pkg/host"
	ghw "github.com/jaypipes/ghw"
	gomock "go.uber.org/mock/gomock"
)

// MockHostInterface is a mock of HostInterface interface.
type MockHostInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHostInterfaceMockRecorder
	isgomock struct{}
}

// MockHostInterfaceMockRecorder is the mock recorder for MockHostInterface.
type MockHostInterfaceMockRecorder struct {
	mock *MockHostInterface
}

// NewMockHostInterface creates a new mock instance.
func NewMockHostInterface(ctrl *gomock.Controller) *MockHostInterface {
	mock := &MockHostInterface{ctrl: ctrl}
	mock.recorder = &MockHostInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostInterface) EXPECT() *MockHostInterfaceMockRecorder {
	return m.recorder
}

// BindDefaultDriver mocks base method.
func (m *MockHostInterface) BindDefaultDriver(pciAddress string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindDefaultDriver", pciAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindDefaultDriver indicates an expected call of BindDefaultDriver.
func (mr *MockHostInterfaceMockRecorder) BindDefaultDriver(pciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindDefaultDriver", reflect.TypeOf((*MockHostInterface)(nil).BindDefaultDriver), pciAddress)
}

// BindDeviceDriver mocks base method.
func (m *MockHostInterface) BindDeviceDriver(pciAddress string, config *v1alpha1.VfConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindDeviceDriver", pciAddress, config)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BindDeviceDriver indicates an expected call of BindDeviceDriver.
func (mr *MockHostInterfaceMockRecorder) BindDeviceDriver(pciAddress, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindDeviceDriver", reflect.TypeOf((*MockHostInterface)(nil).BindDeviceDriver), pciAddress, config)
}

// BindDriverByBusAndDevice mocks base method.
func (m *MockHostInterface) BindDriverByBusAndDevice(device, driver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindDriverByBusAndDevice", device, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindDriverByBusAndDevice indicates an expected call of BindDriverByBusAndDevice.
func (mr *MockHostInterfaceMockRecorder) BindDriverByBusAndDevice(device, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindDriverByBusAndDevice", reflect.TypeOf((*MockHostInterface)(nil).BindDriverByBusAndDevice), device, driver)
}

// EnsureDpdkModuleLoaded mocks base method.
func (m *MockHostInterface) EnsureDpdkModuleLoaded(driver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDpdkModuleLoaded", driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDpdkModuleLoaded indicates an expected call of EnsureDpdkModuleLoaded.
func (mr *MockHostInterfaceMockRecorder) EnsureDpdkModuleLoaded(driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDpdkModuleLoaded", reflect.TypeOf((*MockHostInterface)(nil).EnsureDpdkModuleLoaded), driver)
}

// EnsureVhostModulesLoaded mocks base method.
func (m *MockHostInterface) EnsureVhostModulesLoaded() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureVhostModulesLoaded")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureVhostModulesLoaded indicates an expected call of EnsureVhostModulesLoaded.
func (mr *MockHostInterfaceMockRecorder) EnsureVhostModulesLoaded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureVhostModulesLoaded", reflect.TypeOf((*MockHostInterface)(nil).EnsureVhostModulesLoaded))
}

// GetDriverByBusAndDevice mocks base method.
func (m *MockHostInterface) GetDriverByBusAndDevice(device string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverByBusAndDevice", device)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverByBusAndDevice indicates an expected call of GetDriverByBusAndDevice.
func (mr *MockHostInterfaceMockRecorder) GetDriverByBusAndDevice(device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverByBusAndDevice", reflect.TypeOf((*MockHostInterface)(nil).GetDriverByBusAndDevice), device)
}

// GetNicSriovMode mocks base method.
func (m *MockHostInterface) GetNicSriovMode(pciAddr string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNicSriovMode", pciAddr)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNicSriovMode indicates an expected call of GetNicSriovMode.
func (mr *MockHostInterfaceMockRecorder) GetNicSriovMode(pciAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNicSriovMode", reflect.TypeOf((*MockHostInterface)(nil).GetNicSriovMode), pciAddr)
}

// GetNumaNode mocks base method.
func (m *MockHostInterface) GetNumaNode(pciAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumaNode", pciAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumaNode indicates an expected call of GetNumaNode.
func (mr *MockHostInterfaceMockRecorder) GetNumaNode(pciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumaNode", reflect.TypeOf((*MockHostInterface)(nil).GetNumaNode), pciAddress)
}

// GetParentPciAddress mocks base method.
func (m *MockHostInterface) GetParentPciAddress(pciAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentPciAddress", pciAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentPciAddress indicates an expected call of GetParentPciAddress.
func (mr *MockHostInterfaceMockRecorder) GetParentPciAddress(pciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentPciAddress", reflect.TypeOf((*MockHostInterface)(nil).GetParentPciAddress), pciAddress)
}

// GetVFIODeviceFile mocks base method.
func (m *MockHostInterface) GetVFIODeviceFile(pciAddress string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVFIODeviceFile", pciAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVFIODeviceFile indicates an expected call of GetVFIODeviceFile.
func (mr *MockHostInterfaceMockRecorder) GetVFIODeviceFile(pciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVFIODeviceFile", reflect.TypeOf((*MockHostInterface)(nil).GetVFIODeviceFile), pciAddress)
}

// GetVFList mocks base method.
func (m *MockHostInterface) GetVFList(pfPciAddress string) ([]host.VFInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVFList", pfPciAddress)
	ret0, _ := ret[0].([]host.VFInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVFList indicates an expected call of GetVFList.
func (mr *MockHostInterfaceMockRecorder) GetVFList(pfPciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVFList", reflect.TypeOf((*MockHostInterface)(nil).GetVFList), pfPciAddress)
}

// IsDpdkDriver mocks base method.
func (m *MockHostInterface) IsDpdkDriver(driver string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDpdkDriver", driver)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDpdkDriver indicates an expected call of IsDpdkDriver.
func (mr *MockHostInterfaceMockRecorder) IsDpdkDriver(driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDpdkDriver", reflect.TypeOf((*MockHostInterface)(nil).IsDpdkDriver), driver)
}

// IsKernelModuleLoaded mocks base method.
func (m *MockHostInterface) IsKernelModuleLoaded(moduleName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsKernelModuleLoaded", moduleName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsKernelModuleLoaded indicates an expected call of IsKernelModuleLoaded.
func (mr *MockHostInterfaceMockRecorder) IsKernelModuleLoaded(moduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsKernelModuleLoaded", reflect.TypeOf((*MockHostInterface)(nil).IsKernelModuleLoaded), moduleName)
}

// IsSriovPF mocks base method.
func (m *MockHostInterface) IsSriovPF(pciAddress string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSriovPF", pciAddress)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSriovPF indicates an expected call of IsSriovPF.
func (mr *MockHostInterfaceMockRecorder) IsSriovPF(pciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSriovPF", reflect.TypeOf((*MockHostInterface)(nil).IsSriovPF), pciAddress)
}

// IsSriovVF mocks base method.
func (m *MockHostInterface) IsSriovVF(pciAddress string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSriovVF", pciAddress)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSriovVF indicates an expected call of IsSriovVF.
func (mr *MockHostInterfaceMockRecorder) IsSriovVF(pciAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSriovVF", reflect.TypeOf((*MockHostInterface)(nil).IsSriovVF), pciAddress)
}

// LoadKernelModule mocks base method.
func (m *MockHostInterface) LoadKernelModule(moduleName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadKernelModule", moduleName)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadKernelModule indicates an expected call of LoadKernelModule.
func (mr *MockHostInterfaceMockRecorder) LoadKernelModule(moduleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadKernelModule", reflect.TypeOf((*MockHostInterface)(nil).LoadKernelModule), moduleName)
}

// PCI mocks base method.
func (m *MockHostInterface) PCI() (*ghw.PCIInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PCI")
	ret0, _ := ret[0].(*ghw.PCIInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PCI indicates an expected call of PCI.
func (mr *MockHostInterfaceMockRecorder) PCI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PCI", reflect.TypeOf((*MockHostInterface)(nil).PCI))
}

// RestoreDeviceDriver mocks base method.
func (m *MockHostInterface) RestoreDeviceDriver(pciAddress, originalDriver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeviceDriver", pciAddress, originalDriver)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreDeviceDriver indicates an expected call of RestoreDeviceDriver.
func (mr *MockHostInterfaceMockRecorder) RestoreDeviceDriver(pciAddress, originalDriver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeviceDriver", reflect.TypeOf((*MockHostInterface)(nil).RestoreDeviceDriver), pciAddress, originalDriver)
}

// TryGetInterfaceName mocks base method.
func (m *MockHostInterface) TryGetInterfaceName(pciAddr string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetInterfaceName", pciAddr)
	ret0, _ := ret[0].(string)
	return ret0
}

// TryGetInterfaceName indicates an expected call of TryGetInterfaceName.
func (mr *MockHostInterfaceMockRecorder) TryGetInterfaceName(pciAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetInterfaceName", reflect.TypeOf((*MockHostInterface)(nil).TryGetInterfaceName), pciAddr)
}

// UnbindDriverByBusAndDevice mocks base method.
func (m *MockHostInterface) UnbindDriverByBusAndDevice(device string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindDriverByBusAndDevice", device)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindDriverByBusAndDevice indicates an expected call of UnbindDriverByBusAndDevice.
func (mr *MockHostInterfaceMockRecorder) UnbindDriverByBusAndDevice(device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindDriverByBusAndDevice", reflect.TypeOf((*MockHostInterface)(nil).UnbindDriverByBusAndDevice), device)
}
