---
apiVersion: v1
kind: Namespace
metadata:
  name: vf-test3
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vf-test
  namespace: vf-test3
spec:
  config: |-
    {
        "cniVersion": "1.0.0",
        "name": "vf-test3",
        "type": "sriov",
        "vlan": 0,
        "spoofchk": "on",
        "trust": "on",
        "vlanQoS": 0,
        "logLevel": "info",
        "ipam": {
            "type": "host-local",
            "ranges": [
                [
                    {
                        "subnet": "10.0.1.0/24"
                    }
                ]
            ]
        }
    }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: vf-test3
  name: multiple-vf
spec:
  spec:
    devices:
      requests:
      - name: vf
        exactly:
          deviceClassName: sriovnetwork.openshift.io
          count: 2
      config:
        - requests: [ "vf" ]
          opaque:
            driver: sriovnetwork.openshift.io
            parameters:
              apiVersion: sriovnetwork.openshift.io/v1alpha1
              kind: VfConfig
              netAttachDefName: vf-test

---
apiVersion: v1
kind: Pod
metadata:
  namespace: vf-test3
  name: pod0
  labels:
    app: pod
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr0
    image: quay.io/schseba/toolbox:latest
    command:
      - /bin/bash
      - -c
      - sleep INF
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
    resources:
      claims:
      - name: vf
  resourceClaims:
  - name: vf
    resourceClaimTemplateName: multiple-vf
