---
apiVersion: v1
kind: Namespace
metadata:
  name: vf-test1

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: vf-test1
  name: single-vf
spec:
  spec:
    devices:
      requests:
      - name: vf
        exactly:
          deviceClassName: virtualfunction.sriovnetwork.openshift.io
      config:
      - requests: ["vf"]
        opaque:
          driver: virtualfunction.sriovnetwork.openshift.io
          parameters:
            apiVersion: sriovnetwork.openshift.io/v1alpha1
            kind: VfConfig
            netAttachDefName: sriov-vf

---
apiVersion: v1
kind: Pod
metadata:
  namespace: vf-test1
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: vf
  resourceClaims:
  - name: vf
    resourceClaimTemplateName: single-vf
