name: Release

on:
  push:
    branches: [main]
    tags: ['v*']

env:
  GO_VERSION: "1.24.6"
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/schseba/dra-driver-sriov

jobs:
  build-and-push:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            # For tags, use the tag name (e.g., v1.2.3)
            TAG="${{ github.ref_name }}"
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            # For main branch, use latest
            TAG="latest"
          else
            # For other branches, use branch name
            TAG="${{ github.ref_name }}"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Image tag: ${TAG}"

      - name: Build and push container image
        run: |
          export IMAGE_NAME="${{ env.IMAGE_NAME }}"
          export VERSION="${{ steps.tag.outputs.tag }}"
          cd deployments/container
          make centos9
          make push

